name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  simple_animations: ^5.0.0+3
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/agency3.png
    - assets/page-1/images/agency4.jpg
    - assets/page-1/images/agenc2.jpg
    - assets/page-1/images/l1.png
    - assets/page-1/images/agency1.jpg
    - assets/page-1/images/villabuy1.jpg
    - assets/page-1/images/v.jpg
    - assets/page-1/images/p.jpeg
    - assets/page-1/images/mr.jpeg
    - assets/page-1/images/v1.webp
    - assets/page-1/images/mr1.jpg
    - assets/page-1/images/m1.jpg
    - assets/page-1/images/maisonbuy1.jpg
    - assets/page-1/images/couv.jpg
    - assets/page-1/images/villaoffre.webp
    - assets/page-1/images/villa5.jpg
    - assets/page-1/images/appart4.jpg
    - assets/page-1/images/maison4.jpg
    - assets/page-1/images/maison3.jpg
    - assets/page-1/images/appart3.jpg
    -  assets/page-1/images/villa2.jpg
    - assets/page-1/images/villa3.jpg
    -  assets/page-1/images/aparrt2.jpg
    -  assets/page-1/images/maison1.jpg
    - assets/page-1/images/villa1.jpg
    - assets/page-1/images/appart1.webp
    - assets/page-1/images/right-arrow-1.png
    - assets/page-1/images/logof-1.png
    - assets/page-1/images/group-1.png
    - assets/page-1/images/imgage-3-1.png
    - assets/page-1/images/group-1-Zoh.png
    - assets/page-1/images/rectangle-1583.png
    - assets/page-1/images/image-2-1.png
    - assets/page-1/images/group-1-oa3.png
    - assets/page-1/images/right-arrow-1-GGb.png
    - assets/page-1/images/user.png
    - assets/page-1/images/group.png
    - assets/page-1/images/group-1-Cj5.png
    - assets/page-1/images/group-1-x99.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/u-plus.png
    - assets/page-1/images/group-1-uNT.png
    - assets/page-1/images/house-searching-cuate.png
    - assets/page-1/images/h-1-bg.png
    - assets/page-1/images/right-arrow-1-89H.png
    - assets/page-1/images/lock.png
    - assets/page-1/images/indicator.png
    - assets/page-1/images/group-1-TJb.png
    - assets/page-1/images/vector-gUB.png
    - assets/page-1/images/search-normal-1-3.png
    - assets/page-1/images/group-1-zSF.png
    - assets/page-1/images/undrawadventuremaphnin-2.png
    - assets/page-1/images/vector-emh.png
    - assets/page-1/images/undrawadventuremaphnin-2-Xyu.png
    - assets/page-1/images/right-arrow-1-6HZ.png
    - assets/page-1/images/vector-djy.png
    - assets/page-1/images/right-arrow-1-2n7.png
    - assets/page-1/images/house-searching-bro.png
    - assets/page-1/images/right-arrow-1-abu.png
    - assets/page-1/images/group-1-Fi3.png
    - assets/page-1/images/mail.png
    - assets/page-1/images/right-arrow-1-rKm.png
    - assets/page-1/images/right-arrow-1-pbu.png
    - assets/page-1/images/right-arrow-1-xqq.png
    - assets/page-1/images/next.png
    - assets/page-1/images/right-arrow-1-dSB.png
    - assets/page-1/images/lock-w7y.png
    - assets/page-1/images/right-arrow-1-8Rq.png
    - assets/page-1/images/at-work-bro.png
    - assets/page-1/images/vector-rHZ.png
    - assets/page-1/images/group-2.png
    - assets/page-1/images/mask-group.png
    - assets/page-1/images/apaa-1-bg.png
    - assets/page-1/images/u-minus.png
    - assets/page-1/images/rectangle-27.png
    - assets/page-1/images/microphone-2-2.png
    - assets/page-1/images/search-normal-1-3-U7D.png
    - assets/page-1/images/group-1-M39.png
    - assets/page-1/images/villa-1-bg.png
    - assets/page-1/images/page-dacceuil.png
    - assets/page-1/images/u-plus-Hij.png
    - assets/page-1/images/right-arrow-1-AqR.png
    - assets/page-1/images/indicator-RLX.png
    - assets/page-1/images/vector-HKR.png
    - assets/page-1/images/microphone-2-2-AQs.png
    - assets/page-1/images/group-1-1pP.png
    - assets/page-1/images/u-minus-XgP.png
    - assets/page-1/images/group-1-THm.png
    - assets/page-1/images/auto-group-ffmd.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
